

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
#  datasource:
#    url: jdbc:mysql://localhost:3306/notes_app?useSSL=false
#    username: root
#    password: password
  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#    hiberate:
    # Hibernate ddl auto (create, create-drop, validate, update)
#      ddl-auto: update

  cloud:
    config:
      server:
        git:
          uri: ${HOME}/config-repo
        prefix: /config
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080