server:
  port: 8877
spring:
  boot:
    admin:
      url:  http://localhost:8080
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

